version: "2.0"
services:
  mysql:
    container_name: mysql_server
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=America/Sao_Paulo
  apache_php:
    container_name: apache_php
    image: gabrielduarte/apache_php:latest 
    ports:
      - "80:80"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./webapp:/home/webapps/